config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "services", to: "pages#services"
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  post "schedule_consultation", to: "consultations#schedule", as: "schedule_consultation"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  def schedule
    Rails.logger.info("Received parameters: #{params.inspect}")
    form_data = {
      name: params[:name],
      business_name: params[:business_name],
      email: params[:email],
      phone: params[:phone],
      monthly_billing: params[:monthly_billing],
      number_of_providers: params[:number_of_providers],
      total_ar: params[:total_ar],
      message: params[:message]
    }

    ConsultationMailer.schedule_consultation(form_data).deliver_now
    redirect_to root_path, notice: "Your consultation request has been sent!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def services
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Medi Plus" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <%= yield %>
</body>

</html>

app/views/pages/about.html.erb
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="Site keywords here">
    <meta name="description" content="">
    <meta name='copyright' content=''>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MediTechBilling</title>
    <link rel="icon" href="<%= asset_path('favicon.png') %>">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<%= asset_path('application.css') %>">
</head>

<body>
    <header class="header">
        <div class="topbar">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-5 col-12">
                    </div>
                    <div class="col-lg-6 col-md-7 col-12">
                        <ul class="top-contact">
                            <li><i class="fa fa-phone"></i>+19543864393</li>
                            <li><i class="fa fa-envelope"></i><a>meditechbilling.us@gmail.com</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-inner">
            <div class="container">
                <div class="inner">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-12">
                            <div class="logo">
                                <a href="<%= root_path %>"><%= image_tag 'medi-logo.png', alt: '#', style: "width: 31%; padding-bottom: 10px;" %></a>
                            </div>
                            <div class="mobile-nav"></div>
                        </div>
                        <div class="col-lg-7 col-md-9 col-12" style="padding-top: 10px;">
                            <div class="main-menu">
                                <nav class="navigation">
                                    <ul class="nav menu">
                                        <li class="">
                                            <a href="<%= root_path %>">Home </a>
                                        </li>
                                        <li><a href="<%= about_path %>">About Us</a></li>
                                        <li>
                                            <a href="<%= services_path %>">Services<i class="icofont-rounded-down"></i></a>
                                            <ul class="dropdown">
                                                <li><a href="<%= root_path %>">Complete RCM Solutions</a></li>
                                                <li><a href="<%= root_path %>">Accounts Receivable</a></li>
                                                <li><a href="<%= root_path %>">Payment Reconciliation</a></li>
                                                <li><a href="<%= root_path %>">Claims Scrubber/Validation</a></li>
                                                <li><a href="<%= root_path %>">Accurate Coding</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="<%= contact_path %>">Contact Us</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-lg-2 col-12" style="padding-top: 10px;">
                            <div class="get-quote">
                                <a href="<%= contact_path %>" class="btn">Schedule Consultation</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="breadcrumbs-about" style="background-image:url('<%= asset_path('about-us.jpg') %>');">
        <div class="container">
            <div class="bread-inner">
                <div class="row">
                    <div class="col-6">
                        <h2>About Us</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="contact-us section section-background">
        <div style="justify-items: center;">
            <p style="color: black;font-size: medium;">
                One of the aim is focuses on increasing the profitability of your medical practice, assisting you to sustain it, and increasing patient focus.
            </p>
            <p style="color: black;font-size: medium;">We manage better information for better results and outcomes.</p>
        </div>
    </section>
    <section class="about-us section-background" style="padding-top: 50px;">
        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <%= image_tag 'vision.png', alt: 'rcm', style: "float: inline-start; width: 100%;" %>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12" style="align-content: center;">
                    <div class="elementor-widget-container">
                        <h2 class="elementor-heading-title elementor-size-default">Our <span style="color:black; text-decoration: underline; text-decoration-color: #1d6ea3">Vision</span></h2>
                    </div>
                    <p style="text-align: justify; font-size: 16px; line-height: 1.6; margin-bottom: 24px; font-weight: 400;">
                        At MTB Solutions, we envision a healthcare landscape where medical practices thrive through streamlined processes, empowered by our innovative medical billing and management services. Our vision is to be the leading provider of efficient solutions that enhance profitability, sustainability, and patient focus.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="about-us section-background" style="padding: 50px 0;">
        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12" style="align-content: center;">
                    <div class="elementor-widget-container">
                        <h2 class="elementor-heading-title elementor-size-default">Our <span style="color:black; text-decoration: underline; text-decoration-color: #1d6ea3">Mission</span></h2>
                    </div>
                    <p style="text-align: justify; font-size: 16px; line-height: 1.6; margin-bottom: 24px; font-weight: 400;">
                        Our mission at MTB Solutions is to deliver skillful medical billing and management services that eliminate hassles for medical practices and affiliated insurance matters. Through our team of experienced Healthcare IT Solution Providers and our meticulously developed medical billing module, we aim to not only ensure accuracy and efficiency but also to save valuable time and resources.
                    </p>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <%= image_tag 'our-mission.png', alt: 'rcm', style: "float: inline-end; width: 100%;" %>
                </div>
            </div>
        </div>
    </section>
    <footer id="footer" class="footer ">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-12" style="justify-items: center;">
                        <div class="single-footer">
                            <div class="logo">
                                <a href="<%= root_path %>"><%= image_tag 'white-logo.png', alt: '#', style: "width: 30%;" %></a>
                            </div>
                            <ul class="mt-2">
                                <li><i style="color: #FFFFFF;" class="fa fa-envelope"></i><a style="color: #FFFFFF; padding-left: 10px; align-self: center;">meditechbilling.us@gmail.com</a></li>
                                <li style=" color: #FFFFFF;"><i style="color: #FFFFFF; padding-right: 10px;" class="fa fa-phone"></i>+19543864393</li>
                            </ul>
                        </div>
                    </div>
                    <div class=" col-lg-4 col-md-6 col-12">
                        <div class="single-footer f-link">
                            <h2>Important Links</h2>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-12">
                                    <ul>
                                        <li><a href="<%= root_path %>"><i class="fa fa-caret-right" aria-hidden="true"></i>Home</a></li>
                                        <li><a href="<%= about_path %>"><i class="fa fa-caret-right" aria-hidden="true"></i>About Us</a></li>
                                        <li><a href="<%= services_path %>"><i class="fa fa-caret-right" aria-hidden="true"></i>Services</a></li>
                                        <li><a href="<%= contact_path %>"><i class="fa fa-caret-right" aria-hidden="true"></i>Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-12">
                        <div class="single-footer">
                            <h2>Follow Us</h2>
                            <ul class="social">
                                <li><a href="#"><i class="icofont-facebook"></i></a></li>
                                <li><a href="#"><i class="icofont-instagram"></i></a></li>
                                <li><a href="#"><i class="icofont-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="<%= asset_path('js/jquery.min.js') %>"></script>
    <script src="<%= asset_path('js/jquery-migrate-3.0.0.js') %>"></script>
    <script src="<%= asset_path('js/jquery-ui.min.js') %>"></script>
    <script src="<%= asset_path('js/easing.js') %>"></script>
    <script src="<%= asset_path('js/colors.js') %>"></script>
    <script src="<%= asset_path('js/popper.min.js') %>"></script>
    <script src="<%= asset_path('js/bootstrap-datepicker.js') %>"></script>
    <script src="<%= asset_path('js/jquery.nav.js') %>"></script>
    <script src="<%= asset_path('js/slicknav.min.js') %>"></script>
    <script src="<%= asset_path('js/jquery.scrollUp.min.js') %>"></script>
    <script src="<%= asset_path('js/niceselect.js') %>"></script>
    <script src="<%= asset_path('js/tilt.jquery.min.js') %>"></script>
    <script src="<%= asset_path('js/owl-carousel.js') %>"></script>
    <script src="<%= asset_path('js/jquery.counterup.min.js') %>"></script>
    <script src="<%= asset_path('js/steller.js') %>"></script>
    <script src="<%= asset_path('js/wow.min.js') %>"></script>
    <script src="<%= asset_path('js/jquery.magnific-popup.min.js') %>"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="<%= asset_path('js/bootstrap.min.js') %>"></script>
    <script src="<%= asset_path('js/main.js') %>"></script>
</body>

</html>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>